<?php
require_once("src/SecurityException.php");
require_once("src/token/SynchronizerToken.php");
require_once("src/token/JsonWebToken.php");
require_once("src/authentication/DAOAuthentication.php");
require_once("src/authentication/XMLAuthentication.php");
require_once("src/authentication/OAuth2Authentication.php");
require_once("src/authentication/SessionPersistenceDriver.php");
require_once("src/authentication/RememberMePersistenceDriver.php");
require_once("src/authentication/SynchronizerTokenPersistenceDriver.php");
require_once("src/authentication/JsonWebTokenPersistenceDriver.php");
require_once("src/authorization/DAOAuthorization.php");
require_once("src/authorization/XMLAuthorization.php");
